### ISSUE TITLE
Error: Can't push from local VS Code to gtihub after downloading repo

### ISSUE THREAD

**Issue by gracel0** [geekwise-grace-liang/bank-app#1]
@climateamante, @geekwise-yuki-xiong, @geekwise-korey-nichols, @geekwise-maria-navarro, @geekwise-deidra-wallert

$ git status
fatal: Not a git repository (or any of the parent directories): .git
bash: parse_git_branch: command not found

**Comment by geekwise-deidra-wallert** [comment]
Did you bring it down via an ssh key?

**Comment by gracel0** [comment]
I clicked download...
